[features]
seeds = false
skip-lint = false
[programs.devnet]
orbit_commission = "9kTSzk3yQZBn2esehyucammd1WJ65GKcVAVCBGMdbcL5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../config/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
